// Kvízové kartičky. correct = pole indexov správnych možností.
// multi: true = viac správnych odpovedí (zaškrtávacie).
export const cards = [
  // ── Rádio / rušičky / SDR ──────────────────────────────
  {
    cat: "Rádio",
    q: "Použití rušičky v kanceláři při tajném obchodním jednání je legální.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Zařízení pro napadení mobilní sítě a nedetekovatelné podvržení komunikace je dražší kvůli šifrování a synchronizaci vysílaných dat.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "Pomocí SDR přijímače lze přijímat rádiové signály všech typů modulací pracující ve frekvenčních rozsazích a šířce pásma daného SDR.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "List papíru může přerušit rádiovou komunikaci.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "Úspěšnost rušení rušičkou je dána výkonovou úrovní rušícího signálu na vstupech jednotlivých přijímačů.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "Zaměření vysílače krátkých rádiových pulsů s dlouhými mezerami je stejně náročné jako u vysílače běžných modulovaných signálů.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Fotografie oblačnosti ze satelitu či meteorologická data z balónů nejsou šifrována a může je přijmout kdokoli vhodným přijímačem.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },

  // ── Mobilní sítě / GPS ─────────────────────────────────
  {
    cat: "Mobilní sítě",
    q: "SIM kartu nelze podvrhnout.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Mobilní sítě",
    q: "Určení pozice mobilního telefonu na základě připojení k BTS je nepřesné.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Mobilní sítě",
    q: "Mobilní telefon s WiFi, ale bez GPS dokáže určit svou polohu.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Mobilní sítě",
    q: "Podle zachyceného CID identifikátoru BTS lze zjistit její umístění a další základní konfigurační parametry.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Mobilní sítě",
    q: "Pilot letadla, pokud neví kde se nachází, nepozná že má podvržená poziční data z GPS (nelze je rozlišit od skutečných).",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },

  // ── Kryptografie ───────────────────────────────────────
  {
    cat: "Kryptografie",
    q: "PGP (Pretty Good Privacy) je centralizovaný model důvěry, který využívá certifikační autority.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Kryptografie",
    q: "PGP je vhodnější pro jednotlivce než pro podniková prostředí.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Ztráta soukromého klíče v PGP může vést k nemožnosti dešifrovat přijaté zprávy.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Digitální podpisy kombinují hashovací algoritmy a asymetrickou kryptografii.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "S/MIME používá X.509 certifikáty a hybridní model správy certifikátů.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "AES patří mezi šifry:",
    options: ["Hashovací funkce", "Symetrické"],
    correct: [1],
  },
  {
    cat: "Kryptografie",
    q: "Který z kryptografických standardů se opírá o složitost problému diskrétního logaritmu?",
    options: ["RSA", "AES", "DH"],
    correct: [2],
  },
  {
    cat: "Kryptografie",
    q: "Kerckhoffsův princip říká:",
    options: [
      "Musím předpokládat, že kryptografické algoritmy nejsou tajné",
      "Kryptografické algoritmy jsou tajné",
      "Pouze klíč je tajný",
    ],
    correct: [0, 2],
    multi: true,
  },
  {
    cat: "Kryptografie",
    q: "Kolik polí hlaviček definuje standard S/MIME?",
    options: ["3", "4", "5", "6"],
    correct: [2],
  },
  {
    cat: "Kryptografie",
    q: "Technika mikroteček patří do:",
    options: [
      "Steganografie",
      "Používá se u steganografie i u kryptografie",
      "Kryptografie",
    ],
    correct: [0],
  },

  // ── Kvantová kryptografie / QKD ───────────────────────
  {
    cat: "Kvantová",
    q: "Jak se nazývá foton, který nese informaci?",
    options: ["Signální", "Qubit (q-bit)", "Nosný foton", "Pilotní"],
    correct: [1],
  },
  {
    cat: "Kvantová",
    q: "V QKD linku je „surový“ klíč distribuován přes kvantový kanál; bez chybovosti příjemce obdrží z původního množství přibližně:",
    options: ["≈ 100 %", "≈ 75 %", "≈ 50 %", "≈ 25 %"],
    correct: [2],
  },
  {
    cat: "Kvantová",
    q: "Heisenbergův princip neurčitosti je základním kamenem:",
    options: [
      "Kvantové kryptografie",
      "Symetrické kryptografie",
      "Hashovacích funkcí",
    ],
    correct: [0],
  },

  // ── Biometrie ─────────────────────────────────────────
  {
    cat: "Biometrie",
    q: "Jaká je hlavní výhoda biometrického snímání žilního systému?",
    options: [
      "Malá velikost snímacího zařízení",
      "Automatická detekce živosti díky přítomnosti hemoglobinu",
      "Možnost snímat z velké vzdálenosti",
      "Nízká cena zařízení",
    ],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "Porovnání 1:N se vztahuje k:",
    options: ["Identifikaci", "Autentizaci", "Verifikaci", "Zamítnutí"],
    correct: [0],
  },
  {
    cat: "Biometrie",
    q: "Porovnání 1:1 se vztahuje k:",
    options: ["Zamítnutí", "Autentizaci", "Identifikaci", "Verifikaci"],
    correct: [3],
  },
  {
    cat: "Biometrie",
    q: "Porovnání 1:MNOHO se vztahuje k:",
    options: ["Zamítnutí", "Identifikaci", "Verifikaci", "Autentizaci"],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "Základní biometrický systém se skládá ze dvou modulů:",
    options: [
      "Modul extrakce příznaků a modulační modul",
      "Registrační modul a verifikační modul",
      "Transformační modul a autentizační modul",
      "Vstupní modul a výstupní modul",
    ],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "Falešně negativní výsledek je definován jako:",
    options: [
      "Výsledek testu, který detekuje stav, když stav není přítomen",
      "Výsledek testu, který detekuje stav, když je stav přítomen",
      "Výsledek testu, který nedetekuje stav, když je stav přítomen",
      "Výsledek testu, který nedetekuje stav, když stav není přítomen",
    ],
    correct: [2],
  },
  {
    cat: "Biometrie",
    q: "Typický anatomický biometrický znak je:",
    options: [
      "Chůze",
      "Průkaz totožnosti",
      "Dynamická forma podpisu",
      "Otisk prstu",
    ],
    correct: [3],
  },
  {
    cat: "Biometrie",
    q: "Optický a kapacitní senzor jsou typická snímací zařízení pro:",
    options: [
      "Rozpoznávání hlasu",
      "Rozpoznávání otisků prstů",
      "Rozpoznávání DNA",
      "Rozpoznávání obličeje",
    ],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "Která z následujících charakteristik NENÍ výhodou rozpoznávání obličeje:",
    options: [
      "Možnost vizuální kontroly nasnímaných dat",
      "Možnost bezkontaktního snímání",
      "Nízká vnitřní variabilita biometrického rysu",
      "Cenová dostupnost základního snímacího zařízení",
    ],
    correct: [2],
  },
  {
    cat: "Biometrie",
    q: "Která z následujících metod NESLOUŽÍ k detekci živosti při snímání otisků prstů:",
    options: [
      "Detekce potu",
      "Spektroskopie",
      "Ultrazvukové snímání",
      "Radiofrekvenční identifikace (RFID)",
    ],
    correct: [3],
  },

  // ── Honeypoty ─────────────────────────────────────────
  {
    cat: "Honeypoty",
    q: "Co NEpatří mezi vlastnosti honeypotu s nízkou mírou interakce:",
    options: [
      "Obtížné nasazení",
      "Vysoké riziko napadení",
      "Jednoduché nasazení",
      "Nižší sběr dat",
    ],
    correct: [0, 1],
    multi: true,
  },
  {
    cat: "Honeypoty",
    q: "Co patří mezi vlastnosti honeypotu s nízkou mírou interakce:",
    options: [
      "Obtížné nasazení",
      "Jednoduché nasazení",
      "Nižší sběr dat",
      "Vysoké riziko napadení",
    ],
    correct: [1, 2],
    multi: true,
  },
  {
    cat: "Honeypoty",
    q: "Mezi typy honeypotů patří:",
    options: [
      "Honeypot s nízkou mírou interakce",
      "Neinteraktivní honeypot",
      "Honeypot s vysokou mírou interakce",
      "Honeypot se střední mírou interakce",
    ],
    correct: [0, 2],
    multi: true,
  },
  {
    cat: "Honeypoty",
    q: "Mezi honeypoty NEpatří:",
    options: ["T-Pot", "Dionaea", "Kippo", "ACL"],
    correct: [3],
  },

  // ── Autentizace / OAuth / SAML / PPP ──────────────────
  {
    cat: "Autentizace",
    q: "Password Grant Type je nejbezpečnější variantou výměny tokenů v protokolu OAuth.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "Pro M2M (machine-to-machine) komunikaci se v protokolu OAuth využívá Client Credential Grant.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Autentizace",
    q: "Narozdíl od jazyka SAML nelze protokol OAuth využít v systémech SSO.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "OAuth je protokol pro výměnu sdíleného tajného klíče.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "Diameter funguje na principu komunikace Peer-to-Peer.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Autentizace",
    q: "Nejčastějším formátem pro definici tokenu u standardu SAML je:",
    options: ["JSON", "XML", "Web Socket", "plain-text"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "Který z autentizačních mechanismů u PPP nemá přesně definovány autentizační metody:",
    options: ["PAP", "EAP", "RADIUS", "CHAP"],
    correct: [1],
  },

  // ── Monitorování sítě ─────────────────────────────────
  {
    cat: "Sítě",
    q: "Toky (flows) jsou grupy paketů se stejnou zdrojovou/cílovou IP adresou, zdrojovým/cílovým portem, případně typem protokolu.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Z níže uvedených pojmů označte ty, které představují základní metriky pro monitorování sítě:",
    options: [
      "Důvěra",
      "Dostupnost",
      "Ztrátovost",
      "Zpoždění",
      "Nepopiratelnost",
    ],
    correct: [1, 2, 3],
    multi: true,
  },
  {
    cat: "Sítě",
    q: "Jaká metoda se nejčastěji využívá pro zachycení, zpracování a analýzu paketů při vysokých rychlostech a velkých tocích dat v síti?",
    options: [
      "Sampling",
      "Traffic classification",
      "Packet Mirroring",
      "Splitting",
    ],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Jakým pojmem se označuje čas: odeslání žádosti na server, její zpracování a následné přijetí odpovědi?",
    options: ["RTT", "Jitter", "Throughput", "Bandwidth", "RTL"],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Pomocí aplikace Ping s využitím protokolu ICMP jsme schopni zjistit:",
    options: ["Round-trip time", "Packet loss", "Bandwidth", "Traceroute"],
    correct: [0, 1],
    multi: true,
  },

  // ── Doplněné z Markdownu ──────────────────────────────
  {
    cat: "Honeypoty",
    q: "Honeynet je síť, obsahující jeden nebo více (maximálně 10) honeypotů.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Staré velké mobilní telefony NMT bylo možné navíc odposlouchávat:",
    options: [
      "i obyčejnou vysílačkou",
      "jen digitálním SDR přijímačem nebo obdobným zařízením",
    ],
    correct: [0],
  },
  {
    cat: "Autentizace",
    q: "Typickým User Agentem je v případě protokolu OAuth:",
    options: ["mobilní aplikace", "nativní aplikace", "LDAP", "prohlížeč"],
    correct: [3],
  },
  {
    cat: "Rádio",
    q: "Širokopásmové systémy jsou odolnější vůči rušení.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Autentizace",
    q: "Z následující nabídky vyberte platné role používané v protokolu OAuth:",
    options: [
      "Resource Owner",
      "Client",
      "Service Provider",
      "Identity Provider",
      "Resource Server",
      "Authorization Server",
    ],
    correct: [0, 1, 4, 5],
    multi: true,
  },
  {
    cat: "Biometrie",
    q: "Které z následujících tvrzení je NESPRÁVNÉ ohledně vlastností biometrických systémů:",
    options: [
      "Měřitelnost určuje, jak snadno lze biometrický rys získat pro měření",
      "Stálost znamená, že biometrický rys se může často měnit během života člověka",
      "Univerzálnost znamená, že každá osoba by měla mít daný biometrický rys",
      "Jedinečnost zajišťuje, že žádné dvě osoby nemají stejný biometrický rys",
    ],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "Falešně pozitivní výsledek je definován jako:",
    options: [
      "výsledek testu, který nedetekuje stav, když je stav přítomen",
      "výsledek testu, který nedetekuje stav, když stav není přítomen",
      "výsledek testu, který detekuje stav, když je stav přítomen",
      "výsledek testu, který detekuje stav, když stav není přítomen",
    ],
    correct: [3],
  },
  {
    cat: "Autentizace",
    q: "Pomocí AAA protokolů jsme schopni spravovat přístup do sítě samotné.",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Jakou EN zkratkou se nazývá soubor kvalifikovaných prostředků pro správu kvalifikovaných podpisů (elektronických pečetí)?",
    options: [
      "QSCD - Qualified Signature Creation Device",
      "eIDAS - electronic IDentification, Authentication and trust Services",
      "S/MIME - Secure/Multipurpose Internet Mail Extension",
      "PGP - Pretty Good Privacy",
      "PostSignum",
    ],
    correct: [0],
  },
  {
    cat: "Biometrie",
    q: "Typický behaviorální biometrický znak je:",
    options: ["Dynamická forma podpisu", "Sítnice", "Obličej", "Otisk prstu"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "Použitím rušičky dojde k:",
    options: [
      "zvýšení úrovně signálu a úrovně šumu",
      "změní se odstup signálu od šumu",
      "zahlcení výstupu vysílače",
      "snížení úrovně signálu a úrovně šumu",
    ],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "Co znamená EER (Equal Error Rate) v biometrickém systému:",
    options: [
      "Bod, kde se míra falešného přijetí (FAR) rovná míře falešného odmítnutí (FRR)",
      "Bod, kde je nejvyšší míra správného přijetí",
      "Bod, kde je systém nejbezpečnější",
      "Bod, kde je systém nejméně bezpečný",
    ],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "MiTM útok je proveditelný u sestavení/distribuce klíče pomocí:",
    options: ["QKD", "Base64", "DH algoritmu"],
    correct: [1, 2],
    multi: true,
  },
  {
    cat: "Kvantová",
    q: "Do polarizačního filtru s dvěma ortogonálními bázemi vstupuje foton, který je polarizován vůči bázím diagonálně:",
    options: [
      "foton projde s pravděpodobností 50 % a změní svou polarizaci",
      "foton projde s pravděpodobností 25 % a nezmění svou polarizaci",
      "foton projde s pravděpodobností 25 % a změní svou polarizaci",
      "foton neprojde",
    ],
    correct: [0],
  },
  {
    cat: "Biometrie",
    q: "Které tvrzení o geometrii ruky jako biometrické metodě je správné:",
    options: [
      "Systém funguje spolehlivě již od 3 let věku",
      "Metoda není vhodná pro špinavé prostředí",
      "Metoda se používá v jaderných elektrárnách USA",
      "Má vyšší přesnost než otisk prstu",
    ],
    correct: [2],
  },
  {
    cat: "Kryptografie",
    q: "V rámci PGP existuje tzv. Web of Trust. Jedná se o centrální server pro sdílení veřejných PGP klíčů.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Kryptografie",
    q: "Která z hashovacích funkcí vytváří obraz o velikosti 128 bitů?",
    options: ["SHA-2", "MD5", "SHA-3", "SHA-1"],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Pro efektivní zaměřování zdroje rádiového signálu je potřeba mít k měřícímu přijímači nebo spektrálnímu analyzátoru připojenu vhodnou všesměrovou anténu.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "Pro ověření identity uživatele je v rámci AAA využívána část:",
    options: ["Authentication", "Authorization", "Accounting", "Access"],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Jaký parametr je primárně využíván pro mapování cesty paketů v síti při využití aplikace Traceroute u protokolu ICMP?",
    options: ["TTL"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "Při použití rušičky GSM signálu v České republice:",
    options: [
      "porušujete zákon",
      "neporušujete zákon",
      "je to povoleno pro firmy",
      "je to povoleno pro domácnosti",
    ],
    correct: [0],
  },
  {
    cat: "Biometrie",
    q: "Který z následujících údajů je biometrický rys fyziologický:",
    options: [
      "otisk prstu",
      "dynamika úhozu na klávesnici",
      "dynamika podpisu",
      "styl chůze",
    ],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Který z pojmů je základní metrikou pro monitorování sítě:",
    options: ["dostupnost", "důvěra", "nepopiratelnost", "autenticita"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Který z následujících protokolů je určen pro správu digitálních certifikátů:",
    options: ["OCSP", "SMTP", "HTTP", "POP3"],
    correct: [0],
  },
  {
    cat: "Biometrie",
    q: "Který z následujících údajů je biometrický rys behaviorální:",
    options: ["sítnice", "dynamika podpisu", "otisk prstu", "geometrie ruky"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "V rámci AAA protokolů znamená Accounting:",
    options: [
      "evidenci a účtování přístupů",
      "ověření identity",
      "autorizaci",
      "šifrování",
    ],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Která z následujících hashovacích funkcí je považována za prolomenou:",
    options: ["MD5", "SHA-2", "SHA-3", "SHA-256"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Která z následujících možností je správná pro symetrickou kryptografii:",
    options: [
      "používá stejný klíč pro šifrování i dešifrování",
      "používá různé klíče",
      "používá pouze veřejný klíč",
      "nevyužívá klíče",
    ],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Odchycení klíče je nejsnáze proveditelné v případě, že je sestaven či distribuován pomocí:",
    options: ["QKD", "Base64", "DH algoritmu"],
    correct: [1],
  },
  {
    cat: "Sítě",
    q: "Velikost ICMP hlavičky je:",
    options: ["8 Bytů", "16 bitů", "4 bity", "4 Byty"],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "ČTÚ monitoruje rádiový provoz na celých frekvenčních pásmech VHF a UHF trvale na celé ploše ČR.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Lze podvrhnout / vyslat falešný obsah i v moderních standardech digitální televize DVB-T, kde je použito složité kódování?",
    options: ["Pravda", "Nepravda"],
    correct: [0],
  },
  {
    cat: "Kryptografie",
    q: "Které z dvojic níže uvedených módů jsou z pohledu funkce nejvíce podobné?",
    options: ["CBC a CFB", "ECB a CBC", "CM a OFB", "CFB a OFB"],
    correct: [3],
  },
  {
    cat: "Kryptografie",
    q: "ElGamal patří mezi šifry:",
    options: ["Hashovací funkce", "Asymetrické", "Symetrické"],
    correct: [1],
  },
  {
    cat: "Kryptografie",
    q: "TLS zajišťuje end-to-end šifrování e-mailové komunikace.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Biometrie",
    q: "EER (Equal Error Rate) se týká dvou funkcí (systémových chyb). Systém je vyvážený, když:",
    options: [
      "FAR a FRR jsou si rovny",
      "FP a TP jsou si rovny",
      "Falešně pozitivní a pravdivě pozitivní jsou si rovny",
      "Senzitivita a specificita jsou si rovny",
    ],
    correct: [0],
  },
  {
    cat: "Rádio",
    q: "K zaměřování zdroje rádiového signálu korelačně-interferometrickou metodou, tedy pomocí měření rozdílu fáze přijímaného signálu, je dostačující:",
    options: ["1 anténa", "3 a více antén", "2 antény"],
    correct: [1],
  },
  {
    cat: "Kryptografie",
    q: "Kvalifikovaný digitální podpis je vždy také důvěryhodný v případě použití u zabezpečení e-mailové komunikace.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "Jak prohlížeč (User Agent) zjistí adresu autorizačního serveru v případě využití protokolu OAuth?",
    options: [
      "Aplikace / Resource Server vyžadující přihlášení prohlížeč přesměruje pomocí 3XX odpovědi na HTTP požadavek",
    ],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Jak se nazývá v oblasti QoS nezaručená služba pro odeslání, přenos a příjem paketů, kterou využívá ve výchozím stavu drtivá většina aktivních prvků?",
    options: ["Best-effort"],
    correct: [0],
  },
  {
    cat: "Sítě",
    q: "Vyberte z možností typy internetového provozu podle jejich současného zastoupení v celkovém objemu přenesených dat v Internetu (od největšího po nejmenší zastoupení):",
    options: [
      "Internetové video, IPTV / video na vyžádání, web/data, sdílení souborů, hraní her",
    ],
    correct: [0],
  },
  {
    cat: "Autentizace",
    q: "OAuth je protokol pro výměnu autentizačních tokenů.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Nejobtížnější krok při pokusu o napadení rádiového přenosu je:",
    options: [
      "Zjištění polarizace napadené antény",
      "Prolomení šifrování",
      "Zjištění typu kódování",
      "Zjištění typu a počtu stavů modulace",
    ],
    correct: [1],
  },
  {
    cat: "Rádio",
    q: "Bez směrové antény nelze zaměřit zdroje rádiových signálů.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Autentizace",
    q: "RADIUS zajišťuje pouze autentizaci (Authentication) a autorizaci (Authorization), nikoliv účtování (Accounting).",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Mobilní sítě",
    q: "Zařízení pro zachytávání zpráv mobilních sítí je velmi nákladné a běžný smrtelník si jej nemůže dovolit.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },
  {
    cat: "Sítě",
    q: "Pasivní monitoring sítě generuje obecně malé množství dat pro další analýzu.",
    options: ["Pravda", "Nepravda"],
    correct: [1],
  },

  // ── Obecná bezpečnost ─────────────────────────────────
  {
    cat: "Bezpečnost",
    q: "Mezi tři cíle počítačové bezpečnosti dle NIST standardu FIPS 199 nepatří:",
    options: ["Autorizace", "Utajení", "Integrita"],
    correct: [0],
  },
];
